# Go
# Build your Go application.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/go

jobs:
- job: Linux
  pool:
    name: default
    demands:
      - agent.location -equals local
      - agent.os -equals Linux

  variables:
    GOPATH: '/tmp/gopath'
    GOBIN:  '$(GOPATH)/bin' # Go binaries path 
    GOROOT: '/usr/local/go1.11' # Go installation path

  steps:
  - task: DownloadSecureFile@1
    displayName: 'Download Alpine Properties'
    inputs:
      secureFile: 'ab6d4017-c393-4e83-9a70-61e54520fc81'

  - task: DownloadSecureFile@1
    displayName: 'Download Windows Properties'
    inputs:
      secureFile: '0f0e6d24-eed9-4d6b-a60a-665139190909'

  - task: DownloadSecureFile@1
    displayName: 'Download Client Certificate'
    inputs:
      secureFile: 'fe048ca3-83a7-4258-857c-db117beea9a2'

  - task: DownloadSecureFile@1
    displayName: 'Download Root CA'
    inputs:
      secureFile: '82883b39-9ca3-4615-ab04-98496959f145'

  - task: DownloadSecureFile@1
    inputs:
      secureFile: myOpenFactory_Development.pem

  - script: |
      export CLIENT_VERSION=`git describe --tags --dirty --always`
      echo '##vso[task.setvariable variable=Client.Version;]'${CLIENT_VERSION}
      echo '##vso[task.prependpath]$(GOBIN)' 
      echo '##vso[task.prependpath]$(GOROOT)/bin'
      export PATH="${GOROOT}/bin:${PATH}"
      export PATH="${GOBIN}:${PATH}"
      mkdir -p $(Build.ArtifactStagingDirectory)/artifact
      echo ${CLIENT_VERSION} > $(Build.ArtifactStagingDirectory)/artifact/version.txt
      pushd /tmp
      go get -u github.com/jstemmer/go-junit-report
      go get -u github.com/goreleaser/goreleaser
      go get -u -d github.com/magefile/mage
      popd
      pushd ${GOPATH}/src/github.com/magefile/mage
      go run bootstrap.go
      popd
      go version
      mage --version
      echo ${CLIENT_VERSION}
      docker login -u "$(AzureCR.USER)" -p "$(AzureCR.TOKEN)" $(AzureCR.URL)
    displayName: 'Set up the workspace'

  - script: |
      cp $(Agent.TempDirectory)/myOpenFactory_Development.pem .
      goreleaser --snapshot --rm-dist
    displayName: 'Build and Bundle'

  - script: |
      go test -v ./... 2>&1 | go-junit-report > $(Build.ArtifactStagingDirectory)/report.xml
      cp $(Build.ArtifactStagingDirectory)/report.xml $(Build.ArtifactStagingDirectory)/artifact/report.xml
    displayName: 'Unit Tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '$(Build.ArtifactStagingDirectory)/report.xml' 

  - script: |
      MYOF_CLIENT_CONFIG=$(Agent.TempDirectory) mage test
    displayName: 'E2E Tests'

  - script: |
      docker tag $(AzureCR.URL)/client:alpine-latest $(AzureCR.URL)/client:$(Build.BuildNumber)-alpine
      docker push $(AzureCR.URL)/client:$(Build.BuildNumber)-alpine
    displayName: 'Upload Docker Images'

  - script: |
      cp ./dist/*.zip $(Build.ArtifactStagingDirectory)/artifact/
      cp ./dist/*.tar.gz $(Build.ArtifactStagingDirectory)/artifact/
      cp ./dist/checksums.txt $(Build.ArtifactStagingDirectory)/artifact/
      cp ./dist/*.sig $(Build.ArtifactStagingDirectory)/artifact/
    displayName: 'Bundle Artifact'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/artifact'
      artifactName: myof-client
    displayName: 'Publish Artifacts'

- job: Release
  dependsOn: Linux
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags'))

  variables:
    GOPATH: '/tmp/gopath'
    GOBIN:  '$(GOPATH)/bin' # Go binaries path 
    GOROOT: '/usr/local/go1.11' # Go installation path

  - script: |
      echo '##vso[task.prependpath]$(GOBIN)' 
      echo '##vso[task.prependpath]$(GOROOT)/bin'
      export PATH="${GOROOT}/bin:${PATH}"
      export PATH="${GOBIN}:${PATH}"
      pushd /tmp
      go get -u github.com/goreleaser/goreleaser
      popd
      docker login -u "$(AzureCR.USER)" -p "$(AzureCR.TOKEN)" $(AzureCR.URL)
    displayName: 'Set up the workspace'

  - task: DownloadSecureFile@1
    inputs:
      secureFile: myOpenFactory_Development.pem
  
  steps:
  - script: |
      cp $(Agent.TempDirectory)/myOpenFactory_Development.pem .
      goreleaser --rm-dist
    displayName: 'Build and Release'