runWaitTime: 10s
log:
  type: STDOUT_TEXT
  level: DEBUG
outbounds:
  - id: nBjCkM
    type: FILE
    settings:
      message:
        path: /tmp/myof/outbound
        extensions:
          - xml
        waitTime: 1s
      errorPath: "/tmp/myof/error"
      successPath: "/tmp/myof/success"
      attachment:
        path: /tmp/myof/attachment
        extensions:
          - sample
        waitTime: 1s
  - id: Gw7fon
    type: FILE
    authName: special
    settings:
      message:
        path: /tmp/myof/outbound_special
        extensions:
          - xml
        waitTime: 1s
      errorPath: "/tmp/myof/error"
      successPath: "/tmp/myof/success"
      attachment:
        path: /tmp/myof/attachment_special
        extensions:
          - sample
        waitTime: 1s
inbounds:
  - id: 0T6Qgn
    type: FILE
    settings:
      path: /tmp/myof/inbound
      attachmentPath: /tmp/myof/attachment_inbound
      attachmentWhitelist:
        - "https://myopenfactory.net/"
  - id: e8eioo
    type: FILE
    authName: special
    settings:
      path: /tmp/myof/inbound_special
      attachmentPath: /tmp/myof/attachment_inbound_special
      attachmentWhitelist:
        - "https://myopenfactory.net/"