runwaittime: 10s
log:
  type: STDOUT_TEXT
outbounds:
  - id: vJ5M24
    type: FILE
    settings:
      message:
        path: "C:/myof/outbound/"
        extensions:
          - xml
        waitTime: 1s
      errorPath: "C:/myof/error"
      successPath: "C:/myof/success"
      attachment:
        path: "C:/myof/attachment"
        extensions:
          - sample
        waitTime: 1s
  - id: jB0nsg
    type: FILE
    authname: special
    settings:
      message:
        path: "C:/myof/outbound_special/"
        extensions:
          - xml
        waitTime: 1s
      errorPath: "C:/myof/error"
      successPath: "C:/myof/success"
      attachment:
        path: "C:/myof/attachment_special"
        extensions:
          - sample
        waitTime: 1s
inbounds:
  - id: Oyy8fp
    type: FILE
    settings:
      path: "C:/myof/inbound/"
      attachmentPath: "C:/myof/attachment_inbound"
      attachmentWhitelist:
        - "https://myopenfactory.net/"
  - id: kTD1YQ
    type: FILE
    authname: special
    settings:
      path: "C:/myof/inbound_special/"
      attachmentPath: "C:/myof/attachment_inbound_special"
      attachmentWhitelist:
        - "https://myopenfactory.net/"